[package]
name = "noir_prove"
type = "bin"
authors = [""]

[dependencies]
poseidon2 = { tag = "v0.3.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon2" }
sha256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/sha256" }
